// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Projectstatus string

const (
	ProjectstatusOnHold     Projectstatus = "OnHold"
	ProjectstatusInProgress Projectstatus = "InProgress"
	ProjectstatusCompleted  Projectstatus = "Completed"
)

func (e *Projectstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Projectstatus(s)
	case string:
		*e = Projectstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Projectstatus: %T", src)
	}
	return nil
}

type NullProjectstatus struct {
	Projectstatus Projectstatus
	Valid         bool // Valid is true if Projectstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Projectstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Projectstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Projectstatus), nil
}

type Taskstatus string

const (
	TaskstatusToDo       Taskstatus = "ToDo"
	TaskstatusInProgress Taskstatus = "InProgress"
	TaskstatusDone       Taskstatus = "Done"
)

func (e *Taskstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Taskstatus(s)
	case string:
		*e = Taskstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Taskstatus: %T", src)
	}
	return nil
}

type NullTaskstatus struct {
	Taskstatus Taskstatus
	Valid      bool // Valid is true if Taskstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Taskstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Taskstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Taskstatus), nil
}

type Userroles string

const (
	UserrolesAdmin   Userroles = "Admin"
	UserrolesManager Userroles = "Manager"
	UserrolesMember  Userroles = "Member"
)

func (e *Userroles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Userroles(s)
	case string:
		*e = Userroles(s)
	default:
		return fmt.Errorf("unsupported scan type for Userroles: %T", src)
	}
	return nil
}

type NullUserroles struct {
	Userroles Userroles
	Valid     bool // Valid is true if Userroles is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserroles) Scan(value interface{}) error {
	if value == nil {
		ns.Userroles, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Userroles.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserroles) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Userroles), nil
}

type Project struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ManagerID uuid.NullUUID
	Status    Projectstatus
}

type RefreshToken struct {
	ID        uuid.UUID
	Userid    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
	Revoked   bool
}

type Task struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	UserID      uuid.NullUUID
	Status      Taskstatus
	Title       string
	Description sql.NullString
}

type Team struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	OwnerID   uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Password  string
	Email     string
	Role      Userroles
}
