// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (created_at, updated_at, name,team_id, manager_id)
VALUES($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, team_id, manager_id, status
`

type CreateProjectParams struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	TeamID    uuid.UUID
	ManagerID uuid.UUID
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.TeamID,
		arg.ManagerID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TeamID,
		&i.ManagerID,
		&i.Status,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectById = `-- name: GetProjectById :one
SELECT id, created_at, updated_at, name, team_id, manager_id, status FROM projects
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProjectById(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectById, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TeamID,
		&i.ManagerID,
		&i.Status,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $1, status = $2, updated_at = $3
WHERE id = $4
RETURNING id, created_at, updated_at, name, team_id, manager_id, status
`

type UpdateProjectParams struct {
	Name      string
	Status    Projectstatus
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TeamID,
		&i.ManagerID,
		&i.Status,
	)
	return i, err
}
