// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTasks = `-- name: CreateTasks :one
INSERT INTO tasks (created_at, updated_at, project_id, title, description, user_id)
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, project_id, user_id, status, title, description
`

type CreateTasksParams struct {
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ProjectID   uuid.UUID
	Title       string
	Description sql.NullString
	UserID      uuid.NullUUID
}

func (q *Queries) CreateTasks(ctx context.Context, arg CreateTasksParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTasks,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Status,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTaskById = `-- name: GetTaskById :one
SELECT id, created_at, updated_at, project_id, user_id, status, title, description FROM tasks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTaskById(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Status,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $1, description=$2 ,user_id=$3, status = $4, updated_at = $5
WHERE id = $6
RETURNING id, created_at, updated_at, project_id, user_id, status, title, description
`

type UpdateTaskParams struct {
	Title       string
	Description sql.NullString
	UserID      uuid.NullUUID
	Status      Taskstatus
	UpdatedAt   time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.UserID,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Status,
		&i.Title,
		&i.Description,
	)
	return i, err
}
