// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (created_at, updated_at, name, owner_id)
VALUES($1, $2, $3, $4)
RETURNING id, created_at, updated_at, name, owner_id
`

type CreateTeamParams struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	OwnerID   uuid.UUID
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.OwnerID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OwnerID,
	)
	return i, err
}

const getTeamByOwner = `-- name: GetTeamByOwner :one
SELECT id, created_at, updated_at, name, owner_id FROM teams
WHERE owner_id = $1
LIMIT 1
`

func (q *Queries) GetTeamByOwner(ctx context.Context, ownerID uuid.UUID) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByOwner, ownerID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OwnerID,
	)
	return i, err
}
