// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user and return access and refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logout user and revoke all refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.LogoutResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh-token": {
            "post": {
                "description": "Get a new access token using a refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.RefreshTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or expired refresh token",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register-admin": {
            "post": {
                "description": "Create a new admin user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register admin user",
                "parameters": [
                    {
                        "description": "Admin registration data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateAdminResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get paginated list of projects (Admin or Manager only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Projects"
                ],
                "summary": "Get all projects",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by team ID",
                        "name": "teamId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by manager ID",
                        "name": "managerId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include task statistics",
                        "name": "withStats",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.ProjectsListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - teamId or managerId required",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Admin or Manager only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new project (Manager only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Projects"
                ],
                "summary": "Create a new project",
                "parameters": [
                    {
                        "description": "Project creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateProjectPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.GetProjectsResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error or manager not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Manager only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update project information (Manager only, must be the project manager)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Projects"
                ],
                "summary": "Update a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Project update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.UpdateProjectPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.GetProjectsResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Must be the project manager",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a project by ID (Manager only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Projects"
                ],
                "summary": "Delete a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Manager only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get paginated list of tasks. Members can only see their own tasks.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Get all tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by project ID (required for Admin/Manager)",
                        "name": "projectId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.TasksListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - projectId required for Admin/Manager",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new task (Manager only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Create a new task",
                "parameters": [
                    {
                        "description": "Task creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateTaksPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.GetTasksResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Manager only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update task information (Manager only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Update a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.UpdateTaskPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.GetTasksResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Manager only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Task not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a task by ID (Manager only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Delete a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.DeleteTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Manager only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Task not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teams": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new team (Admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Create a new team",
                "parameters": [
                    {
                        "description": "Team creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.Team"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Admin only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "User already has a team",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teams/by-owner": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the team owned by the current user (Admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Get team by owner",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.TeamExistsResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Admin only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get paginated list of users (Admin or Manager only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get all users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by email",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Team ID (required)",
                        "name": "teamId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by role (Admin, Manager, Member)",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.UsersListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Admin or Manager only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new user (Admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateUserPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Admin only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/exists-by-email": {
            "get": {
                "description": "Check if a user with the given email exists",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Check if user exists by email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.UserExistsResponse"
                        }
                    },
                    "400": {
                        "description": "Email is required",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update user information (Admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.UpdateUserPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.User"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Admin only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a user by ID (Admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Admin only",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateAdminRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateAdminResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refreshToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.User"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateProjectPayload": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateTaksPayload": {
            "type": "object",
            "required": [
                "projectId",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "projectId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateTeamRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Development Team"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateUserPayload": {
            "type": "object",
            "required": [
                "email",
                "password",
                "role",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "enum": [
                        "Admin",
                        "Manager",
                        "Member"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.Userroles"
                        }
                    ]
                },
                "teamId": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.CreateUserResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.User"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.DeleteTaskResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.GetProjectsResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "doneTasks": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "inProgressTasks": {
                    "type": "integer"
                },
                "managerId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.Projectstatus"
                },
                "teamId": {
                    "type": "string"
                },
                "toDoTasks": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.GetTasksResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "projectId": {
                    "type": "string"
                },
                "projectName": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.Taskstatus"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "$ref": "#/definitions/uuid.NullUUID"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.LoginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refreshToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.User"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.LogoutResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Successfully logged out"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "operation completed successfully"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.ProjectsListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.GetProjectsResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.Pagination"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.RefreshTokenRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.TasksListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_interfaces.GetTasksResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.Pagination"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.TeamExistsResponse": {
            "type": "object",
            "properties": {
                "exists": {
                    "type": "boolean",
                    "example": true
                },
                "team": {
                    "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.Team"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.UpdateProjectPayload": {
            "type": "object",
            "required": [
                "name",
                "status"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        "OnHold",
                        "InProgress",
                        "Completed"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.Projectstatus"
                        }
                    ]
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.UpdateTaskPayload": {
            "type": "object",
            "required": [
                "status",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        "ToDo",
                        "InProgress",
                        "Done"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.Taskstatus"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.UpdateUserPayload": {
            "type": "object",
            "required": [
                "email",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.UserExistsResponse": {
            "type": "object",
            "properties": {
                "exists": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_interfaces.UsersListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.User"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.Pagination"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_models.Projectstatus": {
            "type": "string",
            "enum": [
                "OnHold",
                "InProgress",
                "Completed"
            ],
            "x-enum-varnames": [
                "ProjectstatusOnHold",
                "ProjectstatusInProgress",
                "ProjectstatusCompleted"
            ]
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_models.Taskstatus": {
            "type": "string",
            "enum": [
                "ToDo",
                "InProgress",
                "Done"
            ],
            "x-enum-varnames": [
                "TaskstatusToDo",
                "TaskstatusInProgress",
                "TaskstatusDone"
            ]
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_models.Team": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ownerId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_models.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_models.Userroles"
                },
                "teamId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_models.Userroles": {
            "type": "string",
            "enum": [
                "Admin",
                "Manager",
                "Member"
            ],
            "x-enum-varnames": [
                "UserrolesAdmin",
                "UserrolesManager",
                "UserrolesMember"
            ]
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorBody": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "$ref": "#/definitions/github_com_TobiasRV_challenge-fs-senior_internals_utils.ErrorBody"
                }
            }
        },
        "github_com_TobiasRV_challenge-fs-senior_internals_utils.Pagination": {
            "type": "object",
            "properties": {
                "next_cursor": {
                    "type": "string",
                    "example": "eyJpZCI6IjEyMzQ1In0="
                },
                "prev_cursor": {
                    "type": "string",
                    "example": "eyJpZCI6IjEyMzQ1In0="
                }
            }
        },
        "uuid.NullUUID": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if UUID is not NULL",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Challenge FS Senior API",
	Description:      "API for managing teams, projects, tasks, and users",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
